# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

system-ghc: true
recommend-stack-upgrade: true

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  scm-init: git
  params:
    author-name: Andrey Demidenko
    author-email: a.demidenko@cactus.vision
    copyright: 'Sonus Space'
    github-username: worm2fed

